# -*- coding: utf-8 -*-
"""Saikfunctions22092024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdgzt_yp3LaAod2U-_EPUVbBFyDNpvHo
"""

#Assignment 5:Functions

"""Q1)What is the difference between a function and a method in Python?
Soln. Methods are associated with objects, while functions are not. Methods cannot be called by their name alone, but functions can be called using their name directly. Methods directly access attributes and properties of object they are associated with, functions wouldneed the function as an arguement for the same action.

"""

# method
class greet:
  def hello():
    print("hii there")

greet.hello()

# function
def greet2():
  print("hello there")
greet2()

""" Q2.. Explain the concept of function arguments and parameters in Python

 Soln. Parameters are listed in function definition parenthesis, they define the functions signature, quantity and type of inputs acceptable. Arguements are raw values passed to the function when called.

"""

def add(x,y):# parameters
  return x+y
add(2,4) # arguments

"""Q3.What are the different ways to define and call a function in Python?

Soln. Using def keyword, follwed by function name, adding parameter names, followed by a colon, add statements, and end the function with a return statement.
"""

def sayhii(name):
  print("hello",name)

sayhii("sai")



"""4. What is the purpose of the `return` statement in a Python function?
Soln. Return statement ends execution of the function, any statement after return is not execcuted when function is called.
"""

def sub(x,y):
  return x-y
sub(7,4)

"""Q5  What are iterators in Python and how do they differ from iterables?

Soln. Iterable is an object that any user can iterate over. Iterator is also an object that helps a user in iterating over another object.

Q6 . Explain the concept of generators in Python and how they are defined.

soln. Generator is a function that returns an iterator using yield keyword.
"""

def genf():
  yield 4
  yield 6
  yield 8

for t in genf():
  print(t)

"""Q7. What are the advantages of using generators over regular functions?

Soln. Generators can process large data unlike functions.Generators can return multiple values unlike single value returned by functions.Regular function run till completion, generators can pause and resume later.
"""

def genf():  # generator
  i=1
  print("first")
  yield i+1
  print("second")
  yield i+2
  print("third")
  yield i+3
genobj=genf()
sa=genobj.__next__()
sb=genobj.__next__()
sc=genobj.__next__()
print(sa)
print(sb)
print(sc)

def addtwo(k,l): # function
   return k+l

addtwo(7,9)

"""Q8. What is a lambda function in Python and when is it typically used?

Soln. A nameless function that returns only one expression taking more than one argument.
"""

x=lambda a,b:a*b
print(x(5,7))

"""Q 9.  Explain the purpose and usage of the `map()` function in Python.

Soln. The map function executes a function to each element of an iterable(tuple, list).
"""

def double(x):
  return x*2

a=[6,4,7,2,3]
f=map(double,a)
print(list(f))



"""Q 10. What is the difference between `map()`, `reduce()`, and `filter()` functions in Python?

Soln. Map executes function passed as an argument on each of iterables.
Filter is used to form a new list containing elements that satisfy a certain condition
Reduce returns a single value based on function and iterable passed.
"""

def positive(A):
  return A>=0

S=[6,-7,9,-3,8]
filterS=filter(positive,S)
print("filtered output is")
print(list(filterS))




def double(x): # map
  return x*2

a=[6,4,7,2,3]
f=map(double,a)
print("map output is")
print(list(f))



from functools import reduce  #reduce
def add(x,y):
  return x+y

a=[5,4,2,7]
print("output with reduce is")
print(reduce(add,a))

"""Q11. . Using pen & Paper write the internal mechanism for sum operation using  reduce function on this given  list:[47,11,42,13];

Soln. PFA image

Q12. . Write a Python function that takes a list of numbers as input and returns the sum of all even numbers in
the list.
"""

import numpy as np

l=[7,8,9,6,5,4]
def evenl(x):
  return x%2==0
even2=list(filter(evenl,l))
print("the even elements are")
print(even2)
def add(x,y):
  return x+y
sum=reduce(add,even2)
print(f"the sum of even elements is ",sum)

"""Q13. Create a Python function that accepts a string and returns the reverse of that string"""

A=input("enter the string to be reversed  ")
Ar=A[::-1]
print("reversed string is ",Ar)

"""Q 14. Implement a Python function that takes a list of integers and returns a new list containing the squares of
each number.
"""

A=[4,6,8,7]
def sq(x):
  return x**2

As=list(map(sq,A))
print(As)

"""Q15 .Write a Python function that checks if a given number is prime or not from 1 to 200"""

import math
no=int(input("enter any number between 1 and 200 "))
def is_prime(n):
    if n < 2:
        return "not prime"
    i = 2
    while i*i <= n:
        if n % i == 0:
            return "not prime"
        i += 1
    return "prime"

print(is_prime(no))  # True

"""Q16.  Create an iterator class in Python that generates the Fibonacci sequence up to a specified number of
terms.
"""

def fib(n):
  a,b=0,1
  for i in range(n):
    yield a
    a,b=b,a+b
no=int(input("enter the nnumber of terms needed"))
print(list(fib(no)))

"""Q 17. Write a generator function in Python that yields the powers of 2 up to a given exponent"""

import numpy as np
s=[]
def ser(n):
  for i in range(n):
    a=2**(i+1)
    s.append(a)
  print(list(s))

no=int(input("enter the number of terms needed"))
ser(no)

"""Q 18.  Implement a generator function that reads a file line by line and yields each line as a string."""

file1=open('saik.txt')
lines=file1.readlines()
count=0
for line in lines:
  print("Lines{}:{}".format(count,line.strip()))
  count+=1

"""Q19. Use a lambda function in Python to sort a list of tuples based on the second element of each tuple"""

def sortedlist(t):
  t.sort(key=lambda i:i[1])
  return t
A=[(1,2,3),(4,3,1),(6,1,7)]
print(sortedlist(A))

"""Q 20. Write a Python program that uses `map()` to convert a list of temperatures from Celsius to Fahrenheit"""

Cel=[45,32,33,32,31]
def celtof(cel):
    return (cel*1.8)+32
A=list(map(celtof,Cel))
print(A)

"""Q 21. Create a Python program that uses `filter()` to remove all the vowels from a given string."""

A=input("enter the string   ")
sent=["aeiouAEIOU"]
fA=[]
def vf(s):
  for i in s:
    if i in sent:
         fA.append(i)
    return fA
p=list(vf(A))
print(p)